// Generated by CoffeeScript 1.3.3
(function() {
  var path;

  path = require('path');

  path.decomp = function(fpath) {
    var base, ext, root;
    base = path.basename(fpath);
    root = fpath.replace(base, '');
    ext = path.extname(base);
    base = base.replace(ext, '');
    return [root, base, ext];
  };

  module.exports = path;

}).call(this);
